In [1]:
import numpy as np

In [2]:
x = np.array([1,2,3,4,5,6])
x

array([1, 2, 3, 4, 5, 6])

In [3]:
X = (x-np.mean(x))/np.std(x)
X

array([-1.46385011, -0.87831007, -0.29277002,  0.29277002,  0.87831007,
        1.46385011])

In [4]:
data = np.array([
    [2,4,6,6,7,5],
    [3,5,5,7,8,8]
])

In [5]:
data_st = (data-np.mean(data, axis=1, keepdims=True))/np.std(data, axis=1, keepdims=True)
data_st

array([[-1.83711731, -0.61237244,  0.61237244,  0.61237244,  1.22474487,
         0.        ],
       [-1.64316767, -0.54772256, -0.54772256,  0.54772256,  1.09544512,
         1.09544512]])

In [6]:
matriz = np.cov(data_st, rowvar=True)
matriz

array([[1.2       , 0.93914855],
       [0.93914855, 1.2       ]])

In [7]:
eigVal, eigVec = np.linalg.eigh(matriz)
eigVal, eigVec = eigVal[::-1], eigVec[:,::-1] 

In [8]:
eigVal[0:1]

array([2.13914855])

In [9]:
eigVec[:,0:1]

array([[-0.70710678],
       [-0.70710678]])

In [10]:
i = 0
print(\
    f"The eigen value {eigVal[i]}, corresponds to {eigVec[:,i]}"\
)

The eigen value 2.1391485505499115, corresponds to [-0.70710678 -0.70710678]


In [11]:
eigVal/np.sum(eigVal)

array([0.8913119, 0.1086881])

In [12]:
data.shape

(2, 6)

In [13]:
min(data.shape)

2

In [14]:
mat = np.array([])
for Evec in np.transpose(eigVec):
    row = np.array([])
    for Fvec in np.transpose(data_st):
        row = np.append(row,np.dot(Evec,Fvec))
    print(row)
    mat = np.append(mat, row)
    print(mat)
mat = mat.reshape((2,int(mat.shape[0]/2)))

[ 2.46093311  0.82031104 -0.04571437 -0.82031104 -1.64062207 -0.77459667]
[ 2.46093311  0.82031104 -0.04571437 -0.82031104 -1.64062207 -0.77459667]
[-0.1371431  -0.04571437  0.82031104  0.04571437  0.09142873 -0.77459667]
[ 2.46093311  0.82031104 -0.04571437 -0.82031104 -1.64062207 -0.77459667
 -0.1371431  -0.04571437  0.82031104  0.04571437  0.09142873 -0.77459667]


In [15]:
print(mat)

[[ 2.46093311  0.82031104 -0.04571437 -0.82031104 -1.64062207 -0.77459667]
 [-0.1371431  -0.04571437  0.82031104  0.04571437  0.09142873 -0.77459667]]


In [16]:
np.mean(data, axis=1, keepdims=True)

array([[5.],
       [6.]])

In [17]:
data

array([[2, 4, 6, 6, 7, 5],
       [3, 5, 5, 7, 8, 8]])